site_name: Opentracing Decorator
site_description:  A Python decorator for OpenTracing trace generation.

theme:
    name: 'material'

repo_name: doughepi/opentracing-decorator
repo_url: https://github.com/doughepi/opentracing-decorator
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Quickstart: 'quickstart.md'
    - API: 'api.md'

markdown_extensions:
  - admonition
  - pymdownx.highlight:
        linenums: true
        
  - pymdownx.superfences
  - mkautodoc